theme: jekyll-theme-minimal
title: CIT 281 - Lab 6
description: I joined GitHub, created a lab file, went over classes, created and tested Book & Library classes, and added ISBN and deleted book methods.
